[package]
name = "git_launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = "0.2"
gpui-component = "0.2"
anyhow = "1.0"
rust-embed = { version = "8.7.2", features = ["interpolate-folder-path"] }